export const ENV = {
  BASE_URL: 'https://c.de2solutions.com/mobile_dash/',
  ENDPOINTS: {
    LOGIN: 'users.php',
    STOCK_MASTER: 'stock_master.php',
    SALESMAN: 'salesman.php',
    POST_EVENT_QUOTATION: 'post_event_quotation.php',
    GET_EVENT_QUOTATION_HEADER: 'get_event_quotation_header.php',
    VIEW_DATA: 'view_data.php',
    SUPPLIERS: 'suppliers.php',
    FUNCTION_COSTING: 'function_costing.php',
    GET_FUNCTION_COSTING: 'get_function_costing.php',
    LOCATIONS: 'locations.php',
    LOCAL_PURCHASE_ACCOUNT: 'local_purchase_account.php',
    LOCAL_PURCHASE_PAYMENT_ACCOUNT: 'local_purchase_payment_account.php',
    POST_LOCAL_PURCHASE_RECEIPT: 'post_local_purchase_receipt.php',
    POST_LOCAL_PURCHASE_PAYMENT: 'post_local_purchase_payment.php',
    POST_LOCAL_PURCHASE_MATERIAL: 'post_local_purchase_material.php',
    GET_GL_ACCOUNT: 'dropdown/gl_account.php',
    GL_ACCOUNT_INQUIRY: 'ledger/gl_account_inquiry.php',
    FINANCIAL_OVERVIEW: 'dashboard/financial_overview.php',
    INCOME_AND_EXPENSE: 'dashboard/income_and_expense.php',
    PARENT_ACCOUNT_DETAIL: 'dashboard/parent_account_detail.php',
    DASH_RECEIVABLE: 'dashboard/dash_receivable.php',
    DASH_PAYABLE: 'dashboard/dash_payable.php',
    DASH_BANKS: 'dashboard/dash_banks.php',
    DASH_CATEGORY_WISE_VALUATION: 'dashboard/dash_category_wise_valution.php',
    DASH_LOCATION_WISE_VALUATION: 'dashboard/dash_location_wise_valution.php',
    DASH_ITEM_WISE_VALUATION: 'dashboard/dash_item_wise_valution.php',
  },
};
